"""
IO-VNBD field catalog from the published dataset paper (Data in Brief, 2021)
and the GitHub repo layout (onyekpeu/IO-VNBD).

Vehicle CAN/VBOX files (prefix V-) are 10 Hz, 29 columns.
Smartphone AndroSensor files (prefix S-) are IMU at 10 Hz, phone GPS ~1 Hz, 24 columns.

GitHub stores the CSV bodies in Git LFS. Until LFS objects are downloaded,
Phase 0 uses schema-accurate fixtures under data/fixtures/.
"""

from __future__ import annotations

VEHICLE_COLUMNS = [
    "No of GPS satellites available",
    "Time since start of day",
    "GPS Latitude",
    "GPS Longitude",
    "GPS Velocity",
    "GPS Heading",
    "GPS Height",
    "GPS Vertical velocity",
    "Sample period",
    "Steering angle",
    "Wheel speed front left",
    "Wheel speed front right",
    "Wheel speed rear left",
    "Wheel speed rear right",
    "Yaw rate",
    "Indicated vehicle speed",
    "Indicated longitudinal acceleration",
    "Indicated lateral acceleration",
    "Handbrake activated or not",
    "Gear requested",
    "Gear number",
    "Engine speed",
    "Coolant temperature",
    "Clutch position",
    "Brake pressure",
    "Brake position",
    "Battery voltage",
    "Air temperature",
    "Accelerator pedal position",
]

VEHICLE_UNITS = {
    "No of GPS satellites available": "count",
    "Time since start of day": "s",
    "GPS Latitude": "deg (VBOX files may store minutes; inspect magnitude)",
    "GPS Longitude": "deg (VBOX files may store minutes; inspect magnitude)",
    "GPS Velocity": "km/h",
    "GPS Heading": "deg",
    "GPS Height": "km",
    "GPS Vertical velocity": "km/h",
    "Sample period": "s",
    "Steering angle": "deg",
    "Wheel speed front left": "rad/s",
    "Wheel speed front right": "rad/s",
    "Wheel speed rear left": "rad/s",
    "Wheel speed rear right": "rad/s",
    "Yaw rate": "deg/s",
    "Indicated vehicle speed": "km/h",
    "Indicated longitudinal acceleration": "g",
    "Indicated lateral acceleration": "g",
    "Handbrake activated or not": "0/1",
    "Gear requested": "1-5",
    "Gear number": "1-5",
    "Engine speed": "rpm",
    "Coolant temperature": "degC",
    "Clutch position": "0/1",
    "Brake pressure": "psi",
    "Brake position": "0/1",
    "Battery voltage": "V",
    "Air temperature": "degC",
    "Accelerator pedal position": "%",
}

SMARTPHONE_COLUMNS = [
    "GPS latitude",
    "GPS longitude",
    "GPS altitude",
    "GPS speed",
    "GPS accuracy",
    "GPS orientation",
    "GPS satellites In range",
    "Time since start",
    "Date",
    "Accelerometer X",
    "Accelerometer Y",
    "Accelerometer Z",
    "Gravity X",
    "Gravity Y",
    "Gravity Z",
    "Gyroscope (Yaw)",
    "Gyroscope (Pitch)",
    "Gyroscope (Roll)",
    "Magnetic field X",
    "Magnetic field Y",
    "Magnetic field Z",
    "Orientation (Yaw)",
    "Orientation (Pitch)",
    "Orientation (Roll)",
]

SMARTPHONE_UNITS = {
    "GPS latitude": "deg",
    "GPS longitude": "deg",
    "GPS altitude": "m",
    "GPS speed": "km/h",
    "GPS accuracy": "m",
    "GPS orientation": "deg",
    "GPS satellites In range": "count",
    "Time since start": "ms",
    "Date": "YYYY-MO-DD HH-MI-SS_SSS",
    "Accelerometer X": "m/s^2",
    "Accelerometer Y": "m/s^2",
    "Accelerometer Z": "m/s^2",
    "Gravity X": "m/s^2",
    "Gravity Y": "m/s^2",
    "Gravity Z": "m/s^2",
    "Gyroscope (Yaw)": "rad/s",
    "Gyroscope (Pitch)": "rad/s",
    "Gyroscope (Roll)": "rad/s",
    "Magnetic field X": "uT",
    "Magnetic field Y": "uT",
    "Magnetic field Z": "uT",
    "Orientation (Yaw)": "deg",
    "Orientation (Pitch)": "deg",
    "Orientation (Roll)": "deg",
}

# AndroSensor / VBOX aliases. Keys are normalized (lowercase, punctuation stripped).
# Vehicle and smartphone GPS names differ only by capitalization; keep maps separate.
VEHICLE_ALIASES = {
    "no of gps satellites available": "No of GPS satellites available",
    "sats": "No of GPS satellites available",
    "time since start of day": "Time since start of day",
    "time since start of day seconds": "Time since start of day",
    "gps latitude": "GPS Latitude",
    "latitude": "GPS Latitude",
    "latitude degrees": "GPS Latitude",
    "gps longitude": "GPS Longitude",
    "longitude": "GPS Longitude",
    "longitude degrees": "GPS Longitude",
    "gps velocity": "GPS Velocity",
    "velocity": "GPS Velocity",
    "velocity km hr": "GPS Velocity",
    "gps heading": "GPS Heading",
    "heading": "GPS Heading",
    "heading degrees": "GPS Heading",
    "gps height": "GPS Height",
    "height": "GPS Height",
    "height km": "GPS Height",
    "gps vertical velocity": "GPS Vertical velocity",
    "vertical velocity": "GPS Vertical velocity",
    "sample period": "Sample period",
    "steering angle": "Steering angle",
    "wheel speed front left": "Wheel speed front left",
    "wheel speed front right": "Wheel speed front right",
    "wheel speed rear left": "Wheel speed rear left",
    "wheel speed rear right": "Wheel speed rear right",
    "yaw rate": "Yaw rate",
    "indicated vehicle speed": "Indicated vehicle speed",
    "indicated longitudinal acceleration": "Indicated longitudinal acceleration",
    "indicated lateral acceleration": "Indicated lateral acceleration",
    "handbrake activated or not": "Handbrake activated or not",
    "handbrake 0 or 1": "Handbrake activated or not",
    "handbrake": "Handbrake activated or not",
    "gear requested": "Gear requested",
    "gear requested number fof gear employed 1 5": "Gear requested",
    "gear number": "Gear number",
    "gear number fof gear employed 1 5": "Gear number",
    "engine speed": "Engine speed",
    "coolant temperature": "Coolant temperature",
    "clutch position": "Clutch position",
    "brake pressure": "Brake pressure",
    "brake position": "Brake position",
    "battery voltage": "Battery voltage",
    "air temperature": "Air temperature",
    "accelerator pedal position": "Accelerator pedal position",
}

SMARTPHONE_ALIASES = {
    "gps latitude": "GPS latitude",
    "latitude": "GPS latitude",
    "location latitude": "GPS latitude",
    "gps longitude": "GPS longitude",
    "longitude": "GPS longitude",
    "location longitude": "GPS longitude",
    "gps altitude": "GPS altitude",
    "location altitude m": "GPS altitude",
    "gps speed": "GPS speed",
    "location speed kmh": "GPS speed",
    "gps accuracy": "GPS accuracy",
    "location accuracy m": "GPS accuracy",
    "gps orientation": "GPS orientation",
    "location orientation": "GPS orientation",
    "gps satellites in range": "GPS satellites In range",
    "satellites in range": "GPS satellites In range",
    "time since start": "Time since start",
    "time since start in ms": "Time since start",
    "date": "Date",
    "yyyy mo dd hh mi ss sss": "Date",
    "accelerometer x": "Accelerometer X",
    "accelerometer x ms2": "Accelerometer X",
    "accelerometer y": "Accelerometer Y",
    "accelerometer z": "Accelerometer Z",
    "gravity x": "Gravity X",
    "gravity y": "Gravity Y",
    "gravity z": "Gravity Z",
    "gyroscope yaw": "Gyroscope (Yaw)",
    "gyroscope pitch": "Gyroscope (Pitch)",
    "gyroscope roll": "Gyroscope (Roll)",
    "magnetic field x": "Magnetic field X",
    "magnetic field y": "Magnetic field Y",
    "magnetic field z": "Magnetic field Z",
    "orientation yaw": "Orientation (Yaw)",
    "orientation pitch": "Orientation (Pitch)",
    "orientation roll": "Orientation (Roll)",
}

VEHICLE_REQUIRED = [
    "Time since start of day",
    "GPS Latitude",
    "GPS Longitude",
    "GPS Velocity",
    "Yaw rate",
    "Wheel speed rear left",
    "Wheel speed rear right",
    "Indicated vehicle speed",
    "Indicated longitudinal acceleration",
    "Indicated lateral acceleration",
]

SMARTPHONE_REQUIRED = [
    "Time since start",
    "GPS latitude",
    "GPS longitude",
    "Accelerometer X",
    "Accelerometer Y",
    "Accelerometer Z",
    "Gyroscope (Yaw)",
    "Gyroscope (Pitch)",
    "Gyroscope (Roll)",
]
